canEnforceMinimumPythonVersion = true
condaSolveImplementation = hawk
enableCodeAssistEnvironmentCaching = true
enableLegacyFallback = false
envPackingLogicVersion = 2
org.gradle.caching = true
org.gradle.vfs.watch = false
palantirModelsVersion = 0.2281.0
rootProjectName = rtt-transforms
systemProp.http.connectionTimeout = 600000
systemProp.http.socketTimeout = 600000
systemProp.org.gradle.internal.http.connectionTimeout = 600000
systemProp.org.gradle.internal.http.socketTimeout = 600000
transformsDefaultBranchName = master
transformsLangPythonPluginVersion = 1.1173.0
transformsRepoOrg = JINESH-161f69
transformsRepoPath = /JINESH-161f69/Training/RTT-Programme/code/rtt-transforms
transformsRepoProject = Training
transformsRepoRid = ri.stemma.main.repository.0082fd3e-9c97-4941-b94f-c2e51bdbadf6
transformsVersion = 10.148.0
useCondaLocksForPlatforms = linux-64
useDefaultPython = false
useHawkAsDefaultSolver = true
useHawkUvSolver = true
useIncrementalSolve = true
